modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "catchondefeat"
version = "1.6-neoforge-0.0.0"
displayName = "Catch On Defeat"
authors = "timinc aka Timothy Metcalfe"
description = '''
Adds a new aspect to Pokémon in Cobblemon that, when defeated in 1v1 wild combat, causes them to join the player&#x27;s team.
'''

[[dependencies.catchondefeat]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.catchondefeat]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.66,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.catchondefeat]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6.0,1.7.0)"
ordering = "AFTER"
side = "BOTH"